name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install -y flex bison libcurl4-openssl-dev libncurses-dev
    - name: make
      run: make
      
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        # User defined upload name. Visible in Codecov UI
        name: # optional
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: # optional
        # Path to coverage file to upload
        file: # optional
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: # optional
        # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
        env_vars: # optional
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: false
